version: '3.8'
services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '6500:5432'
  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

volumes:
  postgres:
  redis: